---

# See jupyterbook.org/customize/config.html
title: Executable Notes
author: David VandeBunte
logo: executable-notes.svg
only_build_toc_files: true

# See jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: -1

# See jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: executable-notes-mini.svg
