# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
.dind_login: &dind_login
  image:
    name: registry.gitlab.com/davidvandebunte/cicd:latest
  services:
    - docker:19.03.12-dind
  before_script:
    - docker system info

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  <<: *dind_login
  script:
  - ./build-shared-notes
  - ./content/post/build-jln
  - ./build-executable-notes
  except:
  - master

pages:
  <<: *dind_login
  script:
  - ./build-shared-notes
  - ./content/post/build-jln
  - ./build-executable-notes
  artifacts:
    paths:
    - public
  only:
  - master
