---

.dind_login: &dind_login
  image:
    name: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./build-notes
  artifacts:
    paths:
      - public

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

test:
  <<: *dind_login
  # stackoverflow.com/a/58402821/622049
  environment:
    name: Develop
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  except:
    - master

pages:
  <<: *dind_login
  only:
    - master
