---
name: 2public

windows:
  - git:
  - vim:
      - history -s docker run --rm -it $(it) $(mw) registry.gitlab.com/davidvandebunte/minimal-environment:davidvandebunte
  - jupyter:
      - history -s ./start-jln
