#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

bazel run //hugo:user_hugo_img

echo "${CI_PROJECT_NAME:=personal-notes}"
if [ "$CI_PROJECT_NAME" = "personal-notes" ]; then
    BASE_URL="https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/shared-notes"
fi
time docker run --rm \
    -u "$(id -u)":"$(id -g)" \
    --mount type=bind,source="$(pwd)",target=/src \
    --workdir /src/hugo \
    bazel/hugo:user_hugo_img \
    hugo --enableGitInfo \
    ${BASE_URL:+ --baseURL="$BASE_URL"} \
    -d shared-notes
cp -r hugo/shared-notes public
