#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

date
env
docker system info

if [ "${GITLAB_USER_EMAIL:+x}" ]; then
    url_host=$(git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g")
    git remote set-url origin "https://gitlab-ci-token:${CI_TAG_UPLOAD_TOKEN}@${url_host}"
    git config --global user.email "${GITLAB_USER_EMAIL}"
    git config --global user.name 'GitLab (bot)'
fi

if [ "${AWS_ACCESS_KEY_ID:+x}" ]; then
    python3 -m dvc config --local cache.dir /tmp/dvc-cache
    python3 -m dvc remote modify --local aws access_key_id "$AWS_ACCESS_KEY_ID"
    python3 -m dvc remote modify --local aws secret_access_key "$AWS_SECRET_ACCESS_KEY"
fi

./build_scripts/build-bazel
./build-shared-notes
