#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

./build_scripts/start-brc
./build_scripts/start-dind
./build_scripts/start-bazel
./build_scripts/build-bazel
./build_scripts/push-hugo
./build-shared-notes
./build_scripts/push-jln
