#!/usr/bin/env sh
set -o errexit -o nounset

docker exec --tty --workdir "$(pwd)" \
    bazel-server bazel build //content:extract_build_book

build_path=$(find -H bazel-bin -path "*extract_build_book/tmp/jb")

mkdir -p public
cp -r "$build_path/_build/html" public/executable-notes
