#!/usr/bin/env sh
echo "${CI_PROJECT_NAME:=personal-notes}"
time docker run --rm \
    -u "$(id -u)":"$(id -g)" \
    --mount type=bind,source="$(pwd)",target=/src \
    --workdir /src/hugo \
    registry.gitlab.com/davidvandebunte/${CI_PROJECT_NAME}:user_hugo \
    hugo --enableGitInfo -d shared-notes
cp -r hugo/shared-notes public
