baseurl = "https://davidvandebunte.gitlab.io/shared-notes/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Shared Notes"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

disqusShortname = "https-davidvandebunte-gitlab-io-shared-notes"
googleAnalytics = "UA-140340779-1"

[Params]
  subtitle = "On Software Development"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  # Code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  gcse = "004003376500551729789:ng6sui-ihxu"

[[Params.bigimg]]
  src = "img/triangle.jpg"
  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = "Sphere"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
  desc = "Hexagon"

[Author]
  name = "David James VandeBunte"
  email = "davidvandebunte@gmail.com"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "davidvandebunte"
  github = "davidvandebunte"
  # twitter = "username"
  # reddit = "username"
  linkedin = "davidvandebunte"
  # xing = "username"
  stackoverflow = "users/622049/davidvandebunte"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # keybase = "username"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Math Sample"
    url = "post/2017-03-05-math-sample"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "post/2016-03-08-code-sample"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
