#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

echo "${CI_PROJECT_NAME:=personal-notes}"
docker exec --tty bazel-server bazel build --define project=${CI_PROJECT_NAME} //content:push_hugo_img
./bazel-bin/content/push_hugo_img
