#!/usr/bin/env sh
docker run --rm \
    -p 1313:1313 \
    --mount type=bind,source=$(pwd),target=/src \
    registry.gitlab.com/pages/hugo:latest \
    hugo server -D --bind=0.0.0.0 -b http://192.168.0.104/
