#!/usr/bin/env bash
JPORT=${1:-10005}

# Start a jupyter lab server
# - https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
# - https://github.com/jupyter/docker-stacks/blob/2d9aa71f69f7a623b073769b43998ba0078246ce/base-notebook/start.sh
# - https://jupyterhub.readthedocs.io/en/stable/getting-started/config-basics.html
docker run --rm \
    -p "$JPORT":"$JPORT" \
    --env JUPYTER_ENABLE_LAB=yes \
    --env NB_USER="$USER" \
    --env NB_GID=1000 \
    --volume "$HOME":"$HOME" \
    --volume $(pwd):$(pwd) \
    --user root \
    --workdir $(pwd) \
    $(./packaging/tag) \
    start.sh jupyter lab \
    --port "$JPORT" \
    --notebook-dir $(pwd) \
    --NotebookApp.password='sha1:5970cc8206fe:82124bd5879c43de97768e910e3e13d2534d5a63'
