#!/usr/bin/env sh
set -o errexit -o nounset

echo "${CI_PROJECT_NAME:=personal-notes}"
docker exec --tty --workdir "$(pwd)" \
    bazel-server bazel build --define project=${CI_PROJECT_NAME} //jb:extract_build_book
docker exec --tty --workdir "$(pwd)" \
    bazel-server bazel run --define project=${CI_PROJECT_NAME} //jb:push_jln

cp -r "bazel-bin/jb/extract_build_book/tmp/_build/html" public/executable-notes
rm -f bazel-bin/jb/extract_build_book/tmp/_build/.jupyter_cache/global.db
./build_scripts/push-dvc-dpath \
    jb/jupyter_cache bazel-bin/jb/extract_build_book/tmp/_build/.jupyter_cache/
