#!/usr/bin/env sh
set -o errexit -o nounset

echo "${CI_PROJECT_NAME:=personal-notes}"
# docker exec --tty --workdir "$(pwd)" \
#     bazel-server
bazel build --define project=${CI_PROJECT_NAME} //jb:extract_build_book

# TODO: This push is relatively slow; only enable it if you need to debug an issue with the build.
# Notice the warning associated with pushing the hugo image; could this be faster?
# docker exec --tty --workdir "$(pwd)" \
#   bazel-server bazel run --define project=${CI_PROJECT_NAME} //jb:push_jln

cp -r "bazel-bin/jb/extract_build_book/tmp/_build/html" public/executable-notes

# This file is both timestamped and required for caching to work:
# bazel-bin/jb/extract_build_book/tmp/_build/.jupyter_cache/global.db
bazel_cache="bazel-bin/jb/extract_build_book/tmp/_build/.jupyter_cache"
if ! diff --brief jb/jupyter_cache/executed/ $bazel_cache/executed/; then
    ./build_scripts/push-dvc-dpath \
        bazel-bin/jb/extract_build_book/tmp/_build/.jupyter_cache/ jb/jupyter_cache
fi
