#!/usr/bin/env sh
set -o errexit -o xtrace

DOCKER_CONFIG=/tmp/.ci_docker
export DOCKER_CONFIG

# TODO: Write directly to the config directory. See:
# - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/blob/master/.gitlab/.gitlab-ci.yml#L57
# TODO: Are you failing to push in the public repo on vdd (in CI/CD) because the GitLab credentials
# are only for pushing to the private repository? If you only set them up once, then they can get
# stale. Why do you not update them regularly?
echo "${CI_REGISTRY_USER:=davidvandebunte}"
echo "${CI_REGISTRY:=registry.gitlab.com}"
if [ -n "$CI_REGISTRY_PASSWORD" ]; then
    echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
fi
