#!/usr/bin/env python3
import argparse
import subprocess
import shutil
import sys

from pathlib import Path

from dvc.repo import Repo

def push_dvc_dpath(in_dpath: Path, out_dpath: Path):
    "Push a dvc directory to a git branch"
    repo = Repo(".")
    print(in_dpath)
    print(out_dpath)
    shutil.rmtree(out_dpath)
    push_dpath = shutil.copytree(in_dpath, out_dpath)
    repo.add(str(push_dpath))
    subprocess.check_output(["git", "add", str(push_dpath.parent / "jupyter_cache.dvc")])
    git_status = subprocess.check_output(["git", "status", "--short"])
    print("$ git status --short")
    print(git_status)
    if git_status:
        subprocess.check_output(["git", "commit", "-m", f"{push_dpath.name}: Add dvc edits"])
    repo.push(str(push_dpath) + ".dvc")
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("in_dpath", type=Path)
    parser.add_argument("out_dpath", type=Path)
    args = parser.parse_args()
    return push_dvc_dpath(args.in_dpath.resolve(), args.out_dpath.resolve())


if __name__ == "__main__":
    sys.exit(main())
