#!/usr/bin/env python3
import argparse
import subprocess
import shutil
import sys

from pathlib import Path
from datetime import datetime

from dvc.repo import Repo

def push_dvc_dpath(out_dpath: Path, in_dpath: Path):
    "Push a dvc directory to a git branch"
    repo = Repo(".")
    print(in_dpath.resolve())
    print(out_dpath.resolve())
    shutil.rmtree(out_dpath.resolve())
    push_dpath = shutil.copytree(in_dpath.resolve(), out_dpath.resolve())
    repo.add(str(push_dpath))
    tag_name = "job-" + str(push_dpath.name) + "-" + datetime.now().strftime("%Y%m%d-%H%M%S")
    subprocess.check_output(["git", "add", str(push_dpath.parent)])
    git_status = subprocess.check_output(["git", "status", "--short"])
    print("$ git status --short")
    print(git_status)
    if git_status:
        subprocess.check_output(["git", "commit", "-m", f"{push_dpath.name}: Add dvc edits"])
    subprocess.check_output(["git", "tag", tag_name])
    repo.push(str(push_dpath) + ".dvc")
    subprocess.check_output(["git", "push", "-o", "ci.skip", "origin", tag_name])
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("out_dpath", type=Path)
    parser.add_argument("in_dpath", type=Path)
    args = parser.parse_args()
    return push_dvc_dpath(args.out_dpath, args.in_dpath)


if __name__ == "__main__":
    sys.exit(main())
