#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

start_nginx() {
    docker run --name pn-nginx -p 80:80 \
        -v "$(pwd)":/usr/share/nginx/html:ro -d nginx
}

if [ -z "$(docker ps -q -f name=pn-nginx)" ] && [ "$CI_PROJECT_NAME" = "personal-notes" ]; then
    start_nginx
else
    echo "nginx server already started."
fi
