#!/usr/bin/env sh

# TODO 9.6: Eliminate dind solution and communicate with docker over a unix socket.
# See `transform-docker-image.md` for reasoning.
start_dind() {
  # These commands are based on the instructions here:
  # - https://hub.docker.com/_/docker/
  #
  # We use the same `DOCKER_TLS_CERTDIR` defined in the `.gitlab-ci.yml` file; docker runs with root
  # permissions and can automatically create a directory in /. We can't create a directory in the
  # repository working directory because it is cleaned between jobs by default.
  DOCKER_TLS_CERTDIR="/certs"
  docker run --privileged --name dind-docker -d \
    --network host \
    -e DOCKER_TLS_CERTDIR=/certs \
    -v "${DOCKER_TLS_CERTDIR}":/certs \
    docker:dind
}

# TODO: Edit `/etc/hosts` on local machines to be able to refer to the host as `docker`. For
# example, add `docker` at the end of this line:
# 127.0.0.1       localhost
if [ -z "$(docker ps -q -f name=dind-docker)" ]; then
  # TODO: Also somehow check if we are on a shared GitLab runner and do not start if we are. Perhaps
  # check `CI_RUNNER_DESCRIPTION` or `CI_RUNNER_TAGS` for specific names. Check `GITLAB_CI` to
  # deal with the case where you're running locally.
  start_dind
else
  echo "DIND server already started."
fi
