#!/usr/bin/env sh
set -o errexit -o nounset

start_brc() {
  # We create a system directory (in /) for the bazel-remote cache, optionally mounted on a large
  # disk. We can't create a directory in the repository working directory because it is cleaned
  # between GitLab jobs by default. We can't use a docker volume because the contents are only
  # writable by root, and the author of this image seems to indirectly recommend that it be started
  # as a user. We always start it as the same user regardless of who is running this script (the
  # 1000 user should exist on all machines); other users should have access to the service the
  # container provides on port 9092. We provide a 100GB cache for large docker images; 5GB may not
  # fit even one.
  docker run --detach \
    --network host \
    --name brc \
    -u 1000:1000 \
    -v "/bazel_remote_cache":/data \
    buchgr/bazel-remote-cache \
    --s3.auth_method=access_key \
    --s3.access_key_id "$AWS_ACCESS_KEY_ID" \
    --s3.secret_access_key "$AWS_SECRET_ACCESS_KEY" \
    --s3.bucket=davidvandebunte-bazel-pn \
    --s3.endpoint=s3.us-east-1.amazonaws.com \
    --max_size=100
}

if [ -z "$(docker ps -q -f name=brc)" ]; then
  start_brc
else
  echo "bazel-remote server already started."
fi
