---

# See jupyterbook.org/customize/config.html
title: Executable Notes
author: David VandeBunte
logo: executable-notes.svg

# See jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

repository:
  url: https://gitlab.com/davidvandebunte/davidvandebunte.gitlab.io
  path_to_book: content
  branch: master

# See jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
