#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

start_nginx() {
    docker run --name pn-nginx -p 80:80 \
        -v "$(pwd)":/usr/share/nginx/html:ro -d nginx
}

if [ "${CI_PROJECT_NAME:-x}" = "personal-notes" ]; then
    tree -H '.' --prune -P 'index.html' -L 2 --noreport --charset utf-8 . > out.html
    mv out.html index.html
    if [ -z "$(docker ps -q -f name=pn-nginx)" ]; then
        start_nginx
    else
        echo "nginx server already started."
    fi
fi
