#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

bazel build //jb:rethinking_tar
tar_fpath="$(bazel info bazel-bin)/jb/rethinking_tar.tar"
docker build \
    -t install_rethinking \
    -f install/Dockerfile \
    --no-cache \
    - < "$tar_fpath" > build.log
docker save -o image.tar install_conda_pip
dvc add build.log image.tar
git ci -m "Build install_rethinking docker image on $(hostname)"
