#!/usr/bin/env sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "${CI_REGISTRY_IMAGE:=registry.gitlab.com/davidvandebunte/davidvandebunte.gitlab.io}"
REF_IMG=$CI_REGISTRY_IMAGE:jln

time docker pull "$REF_IMG" || true
DOCKER_BUILDKIT=1 docker build --progress=plain \
    --cache-from "$REF_IMG" \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --tag jln - < "$SCRIPTPATH"/Dockerfile
docker tag jln "$REF_IMG"
docker push $REF_IMG
